import CSVMaker
import logging

# Create and configure logger
logger =  logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(message)s')

file_handler = logging.FileHandler('gamesList.log')
file_handler.setFormatter(formatter)

stream_handler = logging.StreamHandler()
stream_handler.setFormatter(formatter)

logger.addHandler(file_handler)
logger.addHandler(stream_handler)

# https://spin.atomicobj ect.com/2016/04/19/vim-commands-cheat-sheet/
#

# This function uses the list of lines generated by readlines() to read in one
# line at a time then builds a map of data from each game and returns a list of
# all games and associated pgn header info (aka tags) plus moves.
def gamesList(lines):
    gamesList = []
    moves = ''
    addMoves = False
    headerMap = CSVMaker.initializeGameMap()
    for line in lines:
        if line[0:1] == "[":
            if addMoves:
                addMoves = False
                headerMap["Moves_"] = moves
                gamesList.append(headerMap)
                moves = ''
                headerMap = CSVMaker.initializeGameMap()
            keyValue = line[1:-2]
            key = keyValue.split()[0]
            valueIndex = keyValue.find("\"")
            value = keyValue[valueIndex+1:-1]
            if key in headerMap:
                headerMap[key] = value
            else:
                #tried adding logging here but it wasn't working correctly
                print("Error: missing key", key)
        elif line[0:2] == "1.":
            addMoves = True
        if addMoves:
            moves += str(line.rstrip())
    headerMap["Moves_"] = moves
    gamesList.append(headerMap)

    return gamesList